runtime: nodejs
env: flex
skip_files:
  - ^(.*/)?\.ts$
network:
  forwarded_ports:
    - 9001/tcp
    - 9001/udp
manual_scaling:
  instances: 1
env_variables:
  DATABASE_HOST: '146.148.89.71'
  DATABASE_USER: 'forwarding'
  DATABASE_PASSWORD: '6,2Zi6+ez5N8dA!#'