runtime: nodejs
env: flex
skip_files:
  - ^(.*/)?\.ts$
network:
  forwarded_ports:
    - 9001/tcp
    - 9001/udp
manual_scaling:
  instances: 1
env_variables:
  NODE_ENV: "production"
  MEMCACHE_URL: 'memcached-13311.c1.us-central1-2.gce.cloud.redislabs.com:13311'
  MEMCACHE_USERNAME: 'wittylizard'
  MEMCACHE_PASSWORD: 'wittypass'
  DATABASE_HOST: '/cloudsql/wittylizard-168912:us-central1:wittydev'
  DATABASE_USER: 'forwarding'
  DATABASE_PASSWORD: '6,2Zi6+ez5N8dA!#'
  SQL_CLIENT: 'mysql'